### ISSUE TITLE
IngestLDDView Cardinality

### ISSUE THREAD

**Issue by acraugh** [sbn-psi/ldd_utilities#1]
This could be a very handy tool for reviewers inspecting mission dictionaries, as well as providing an alternate form of documentation for any dictionary.  With that in mind,  the cardinality notation ("(1-1)", "(0-1)", etc.), might be a little too obscure for our reviewers or new users.  Is it possible to replace it with human-readable text like "optional" or "required" (if the first number is '0' or anything other than '0', respectively), and an indication of repeatability?  Gets a little tricky, since it's possible to be required a specific number of times, repeatable up to some maximum number; or repeatable as desired. So values like:

- Required (rather than "1-1")
- Optional (rather than "0-1")
- Required 2 times (rather than "2-2")
- Optional, Repeatable (rather than "0-*")
- Required, Repeatable to 4 times (rather than "1-4")
- etc.

Easier and probably sufficient would be to put some explanatory text at the top of the page defining the notation.

**Comment by jstone-psi** [comment]
This is definitely possible, and probably not very difficult.

**Comment by jstone-psi** [comment]
This has now been implemented.
